In [1]:
import numpy as np
array1=np.array([10,30,50,70,90])
print(array1)

[10 30 50 70 90]


In [2]:
import numpy as np
arr=np.array([10,40,67,89])
print(arr[0])
print(arr[3])

10
89


In [3]:
import numpy as np
arr=np.array([23,56,78,87,69])
print(arr[1:4])

[56 78 87]


In [6]:
import numpy as np
arr1=np.array([67,54,33])
arr2=np.array([70,65,45])
arr3=np.array([13,23,45])
print(arr1+arr2+arr3)

[150 142 123]


In [7]:
import numpy as np
a=np.array([2,4,6,8])
print(a*2)

[ 4  8 12 16]


In [8]:
import numpy as np
arr=np.array([10,20,30,40,50])
print("Sum is:",np.sum(arr))
print("Average value is:",np.mean(arr))

Sum is: 150
Average value is: 30.0


In [ ]:
import numpy as np
arr=np.array([54,80,99,67])
print(arr)
print("maximum value : ",np.max(arr))
print("minimum value: ",m